### ISSUE TITLE
Updating to freedesktop runtime 18.08

### ISSUE THREAD

**Issue by FakeShemp** [flathub/com.katawa_shoujo.KatawaShoujo#1]
I've been trying to update the runtime to 18.08, but are running into some problems.

Firstly, `chrpath` does not seem to be available any more. Has it been deprecated in favor of something else?

And above that, renpy seems to complain that it cannot find SDL2 when building (`Could not find required library SDL2.`), which I thought was bundled in the runtime and was found all right with freedesktop 1.6. What am I doing wrong?

**Comment by TingPing** [comment]
I suggest reporting these bugs here: https://gitlab.com/freedesktop-sdk/freedesktop-sdk

I don't believe `chrpath` is deprecated and SDL2 is still there so must be missing something.

**Comment by FakeShemp** [comment]
For people stumbling upon this. It was renpy's buildsystem being stubborn and not automagically finding SDL2 that was the issue.

chrpath is apparently removed from 18.08 though.

**Comment by TingPing** [comment]
I still recommend reporting that to the sdk folks, I'm sure they would add it.

**Comment by FakeShemp** [comment]
@TingPing I did and they're aware of it. They'll just hold back to see if there's any real need to bundle it. My script worked fine without it in the end.
