### ISSUE TITLE
Port to Renpy 8 to fix several bugs

### ISSUE THREAD

**Issue by keftie22** [flathub/com.katawa_shoujo.KatawaShoujo#12]
There are currently many issues I'm aware of with the current flatpak build which, as far as I can tell, are fixed entirely by [this port to Renpy 8](https://github.com/gcammisa/KatawaShoujo-RenPy8) that @gcammisa was graciously able to do for Windows, Mac, and Linux recently that I hope we can also mimic in our build process here.

------------------------

**Greatly improved sharpness, particularly in fullscreen mode**

This is what the current flatpak build looks like in fullscreen mode at 1080p

![6_full](https://user-images.githubusercontent.com/101351551/206884275-1789af39-99cf-48b9-bf84-e28704c219a8.png)

![image](https://user-images.githubusercontent.com/101351551/206884288-d92131f3-4e5f-411d-9d29-608ba57784bb.png)

This is what the Renpy 8 port looks like on the same machine, much easier on the eyes

![8_full](https://user-images.githubusercontent.com/101351551/206884296-bf5358f2-14f0-41d0-9b75-37dcfb38cb98.png)

![image](https://user-images.githubusercontent.com/101351551/206884305-542027b3-99e9-4e5e-9dea-0ad8686e7de4.png)

------------------------

**Multimonitor support**

This game just currently doesn't work in fullscreen on dual monitors, even on Wayland it will sit in between the screens, which is of course just unusable

![6_splash](https://user-images.githubusercontent.com/101351551/206884371-a2ab93ad-15e1-4c16-801a-6d968fdff229.jpg)

![6_settings](https://user-images.githubusercontent.com/101351551/206884381-46929f5a-09c9-40a2-bd2b-b0700ffa8ba1.jpg)

Whereas on the Renpy 8 port it works exactly as intended with both the splash screen and fullscreen sticking to one screen

![8_splash](https://user-images.githubusercontent.com/101351551/206884426-2f0c839c-e625-45f3-ba87-8ee4e790c310.png)

![8_full2](https://user-images.githubusercontent.com/101351551/206884448-1a690276-4f2d-4f20-9c3b-911ff367d91c.jpg)

------------------------

**Working Japanese support**

The current flatpak build gives you this error message upon switching to Japanese and then crashes and can't be opened again, as noted in #9 

![Screenshot from 2022-12-10 21-39-29](https://user-images.githubusercontent.com/101351551/206884520-c82d8be4-0cbb-42b8-b59b-e2f4d53112be.png)

The Renpy 8 port seems to work perfect

------------------------

**Audio muting doesn't summon demons**

This was more an issue with the Renpy 7 version we had before last year with #4, but I have no problems muting the audio without blowing my ear drums out.

---------------------------------------

I'm hoping we are can look at how gcammisa was able to do this port and somehow do the same here because it would be a great improvement. I don't have the skill to do it myself but hopefully since it's already been done with a finished Linux build it won't be too difficult to mimic his build process somehow for flatpak.

Running Fedora 37 Wayland on a 2021 Asus G14 on the vega 8 AMD igpu

Thank you for coming to my TED talk.

**Comment by keftie22** [comment]
Also forgot to mention, on postmarketOS on my oneplus 6 this flatpak is able to load the splash screen but crashes before actually loading the game. I'm unable to test the Renpy 8 port on it since there isn't an arm Linux build for it but since the current flatpak does have one, it may be able to build that with the new version and fix the game but I have no way to confirm that right now.

**Comment by FakeShemp** [comment]
This is cool but I think it should be its own manifest and probably supersede this one if it's a superior project.

**Comment by FakeShemp** [comment]
Solved with #13
