### ISSUE TITLE
The mute button has become the ear rape button on Debian 10

### ISSUE THREAD

**Issue by ElonSatoshi** [flathub/com.katawa_shoujo.KatawaShoujo#4]
How to reproduce:

1. On Debian 10 Buster, run `flatpak install flathub com.katawa_shoujo.KatawaShoujo`, then `flatpak run com.katawa_shoujo.KatawaShoujo`
2. For your safety, unplug any headphones and turn the volume down to 50% or less
3. Press M

Expected result:

Sound, or at least music should stop. This expectation is based on the icon that shows up in the upper right corner when I press M that depicts a music note with a circle around it and a line through it.

Reality:

What was once a peaceful piano track becomes very loud and glitchy electric sounds. Let me know if you need me to record this happening with my phone.

**Comment by pizzadude** [comment]
Confirmed on Fedora 32

**Comment by FakeShemp** [comment]
Updating all components does not help, so either its an upstream or runtime issue.

**Comment by Steinhagen** [comment]
This issue is still reproducible after the 20.08 runtime update.

**Comment by FakeShemp** [comment]
Solved with #8
